[versions]
springBoot = "4.1.0"
springModulith = "2.1.0"
pdfbox = "3.0.8"
awsSdk = "2.50.2"

[libraries]
spring-boot-starter-web = { module = "org.springframework.boot:spring-boot-starter-web" }
pdfbox = { module = "org.apache.pdfbox:pdfbox", version.ref = "pdfbox" }
spring-boot-starter-webmvc-test = { module = "org.springframework.boot:spring-boot-starter-webmvc-test" }
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test" }
spring-boot-starter-data-jpa = { module = "org.springframework.boot:spring-boot-starter-data-jpa" }
spring-boot-starter-flyway = { module = "org.springframework.boot:spring-boot-starter-flyway" }
spring-boot-starter-security = { module = "org.springframework.boot:spring-boot-starter-security" }
spring-boot-starter-actuator = { module = "org.springframework.boot:spring-boot-starter-actuator" }
spring-boot-starter-validation = { module = "org.springframework.boot:spring-boot-starter-validation" }
spring-boot-testcontainers = { module = "org.springframework.boot:spring-boot-testcontainers" }
postgresql = { module = "org.postgresql:postgresql" }
flyway-database-postgresql = { module = "org.flywaydb:flyway-database-postgresql" }
testcontainers-postgresql = { module = "org.testcontainers:testcontainers-postgresql" }
spring-modulith-starter-core = { module = "org.springframework.modulith:spring-modulith-starter-core", version.ref = "springModulith" }
spring-modulith-starter-test = { module = "org.springframework.modulith:spring-modulith-starter-test", version.ref = "springModulith" }
aws-s3 = { module = "software.amazon.awssdk:s3", version.ref = "awsSdk" }
aws-url-connection-client = { module = "software.amazon.awssdk:url-connection-client", version.ref = "awsSdk" }

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "springBoot" }
spring-dependency-management = { id = "io.spring.dependency-management", version = "1.1.7" }
